name: tarot_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1  # Uyumlu firebase_core sürümü
  firebase_auth: ^5.4.1   # firebase_auth'un uyumlu sürümü
  firebase_messaging: ^15.0.0 # Uyumlu firebase_messaging sürümü
  firebase_analytics: ^11.4.1 # Uyumlu firebase_analytics sürümü
  cloud_firestore: ^5.6.2 
  in_app_purchase: ^3.0.0
  provider: ^6.0.0
  image_picker: ^1.1.2
  http: ^1.2.2 # http paketini değiştirmedik
  translator: ^1.0.3+1
  image: ^4.0.15 # Image işleme için kullanılan paket
  audioplayers: ^6.1.0 # Audioplayers paketini uyumlu sürüme çekiyoruz
  rive: ^0.13.20 # Rive paketini uyumlu sürüme çekiyoruz
  fluttertoast: ^8.2.10
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^15.0.0
  google_sign_in: ^5.4.0
  intl: ^0.18.0

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8
  flutter_fortune_wheel: ^1.3.2
  shared_preferences: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/tarot/images/
    - assets/tarot/images/spinwheel.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true