// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNQ42UYxYf-FGnT69TbFcVSbequbHEzxk',
    appId: '1:686940629306:web:4eb9a9eb43a1d46de28803',
    messagingSenderId: '686940629306',
    projectId: 'tarotail',
    authDomain: 'tarotail.firebaseapp.com',
    storageBucket: 'tarotail.firebasestorage.app',
    measurementId: 'G-1CFSXRTSPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKcE7e9fk2WLWyePD_oTxnySouyeg-2_g',
    appId: '1:686940629306:android:67434424e6d72a78e28803',
    messagingSenderId: '686940629306',
    projectId: 'tarotail',
    storageBucket: 'tarotail.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQG8w4BchMhsP4_TTnVSXsckGm2CZO_LE',
    appId: '1:686940629306:ios:9c2b55fb346fb501e28803',
    messagingSenderId: '686940629306',
    projectId: 'tarotail',
    storageBucket: 'tarotail.firebasestorage.app',
    iosBundleId: 'com.example.tarotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQG8w4BchMhsP4_TTnVSXsckGm2CZO_LE',
    appId: '1:686940629306:ios:9c2b55fb346fb501e28803',
    messagingSenderId: '686940629306',
    projectId: 'tarotail',
    storageBucket: 'tarotail.firebasestorage.app',
    iosBundleId: 'com.example.tarotApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNQ42UYxYf-FGnT69TbFcVSbequbHEzxk',
    appId: '1:686940629306:web:607c92c86062dca6e28803',
    messagingSenderId: '686940629306',
    projectId: 'tarotail',
    authDomain: 'tarotail.firebaseapp.com',
    storageBucket: 'tarotail.firebasestorage.app',
    measurementId: 'G-EWKT2TMTJ5',
  );
}
